receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      network:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
          system.cpu.logical.count:
            enabled: true
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      process:
      load:

  filelog:
    include: [ /var/log/*.log ]
    start_at: beginning

processors:
  resourcedetection:
    detectors: ["system"]
  elasticinframetrics:
  batch:
    timeout: 5s
    send_batch_size: 50

exporters:
  debug:
    verbosity: basic
  elasticsearch:
    endpoints: https://<your elasticsearch endpoints>:9243
    api_key: <secret API keys >
    logs_index: "otel-collector-logs"
    tls:
      insecure: false
      insecure_skip_verify: true
    mapping:
      mode: ecs

service:
  pipelines:
    metrics/host:
      receivers: [hostmetrics]
      processors: [resourcedetection, batch, elasticinframetrics]
      exporters: [elasticsearch, debug]

    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [debug, elasticsearch]
